# Generated by Django 6.0.2 on 2026-03-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AkademikPersonel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=100)),
                ('unvan', models.CharField(choices=[('Prof.', 'Profesör'), ('Doç.', 'Doçent'), ('Dr.', 'Doktor Öğretim Üyesi'), ('Arş. Gör.', 'Araştırma Görevlisi')], max_length=50)),
                ('ozgecmis_tr', models.TextField(help_text='Türkçe Özgeçmiş')),
                ('ozgecmis_en', models.TextField(help_text='İngilizce Özgeçmiş')),
                ('fotograf', models.ImageField(blank=True, null=True, upload_to='ekip/')),
                ('sira', models.IntegerField(default=0, help_text='Sitede görünme sırası')),
            ],
        ),
        migrations.CreateModel(
            name='Proje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik_tr', models.CharField(max_length=200)),
                ('baslik_en', models.CharField(max_length=200)),
                ('aktif_mi', models.BooleanField(default=True)),
                ('baglanti_adresi', models.CharField(help_text='Örn: geodezik-modelleme', max_length=100)),
            ],
        ),
    ]
