# Generated by Django 6.0.2 on 2026-03-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_proje'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hakkimizda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200)),
                ('icerik_tr', models.TextField(help_text='Türkçe İçerik')),
                ('icerik_en', models.TextField(help_text='İngilizce İçerik')),
                ('fotograf', models.ImageField(blank=True, null=True, upload_to='hakkimizda/')),
            ],
        ),
    ]
