# Generated by Django 6.0.2 on 2026-03-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_hakkimizda'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hakkimizda',
            options={'verbose_name': 'Hakkımızda Bilgisi', 'verbose_name_plural': 'Hakkımızda Bilgileri'},
        ),
        migrations.RemoveField(
            model_name='hakkimizda',
            name='baslik',
        ),
        migrations.RemoveField(
            model_name='hakkimizda',
            name='fotograf',
        ),
        migrations.AddField(
            model_name='hakkimizda',
            name='baslik_en',
            field=models.CharField(default='About Us', max_length=200, verbose_name='Title (EN)'),
        ),
        migrations.AddField(
            model_name='hakkimizda',
            name='baslik_tr',
            field=models.CharField(default='Hakkımızda', max_length=200, verbose_name='Başlık (TR)'),
        ),
        migrations.AlterField(
            model_name='hakkimizda',
            name='icerik_en',
            field=models.TextField(verbose_name='Content (EN)'),
        ),
        migrations.AlterField(
            model_name='hakkimizda',
            name='icerik_tr',
            field=models.TextField(verbose_name='İçerik (TR)'),
        ),
    ]
