# Generated by Django 6.0.2 on 2026-03-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_hakkimizda_options_remove_hakkimizda_baslik_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='akademikpersonel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='akademikpersonel',
            name='uzmanlik_alanlari_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Uzmanlık Alanları (EN)'),
        ),
        migrations.AddField(
            model_name='akademikpersonel',
            name='uzmanlik_alanlari_tr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Uzmanlık Alanları (TR)'),
        ),
    ]
