version: '3.8'

services:
  # 1. Veritabanı Kapsülü
  db:
    image: postgres:15-alpine
    container_name: histech_db
    environment:
      POSTGRES_DB: insaat-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d insaat-db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. Django Kapsülü
  backend:
    build:
      context: ./backend
    container_name: histech_backend
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - static_volume:/app/staticfiles  # Admin tasarımları için köprü
      - media_volume:/app/media         # Medya dosyaları için köprü
    env_file:
      - ./backend/.env  
    restart: always
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000

  # 3. React / Nginx Kapsülü
  frontend:
    build: ./frontend
    container_name: histech_frontend
    env_file:
      - ./backend/.env
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - static_volume:/app/staticfiles  # Nginx'in admin tasarımlarını okuyabilmesi için köprü
      - media_volume:/app/media         # Nginx'in yüklenen fotoğrafları okuyabilmesi için köprü
    restart: always

# 4. Ortak Köprülerin (Named Volumes) Tanımlanması (Hayati Eksik Burasıydı)
volumes:
  static_volume:
  media_volume: